openapi: 3.0.0
info:
  title: Sensors API
  version: 1.0.0
  description: API for updating fridge temperature and movement sensors.

servers:
  - url: https://fridgebridge.simplecharity.com

paths:
  /fridge/sensor/temperature:
    post:
      summary: Update fridge temperature sensor
      description: Updates the temperature readings of a fridge sensor. Only accessible by fridge administrator.
      security:
        - BearerAuth: []
      requestBody:
        description: Temperature update payload
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FridgeTempDTO"
      responses:
        "200":
          description: Temperature update sent successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Invalid request body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "401":
          description: Unauthorized or not a legal entity.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"

  /fridge/sensor/movement:
    post:
      summary: Update fridge movement sensor
      description: Updates the movement readings of a fridge sensor. Only accessible by fridge administrator.
      security:
        - BearerAuth: []
      requestBody:
        description: Movement update payload
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FridgeMovementDTO"
      responses:
        "200":
          description: Movement update sent successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Invalid request body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "401":
          description: Unauthorized or not a legal entity.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FridgeTempDTO:
      type: object
      required:
        - fridge_id
        - sensor_id
        - temp
      properties:
        fridge_id:
          type: integer
          example: 123
        sensor_id:
          type: integer
          example: 456
        temp:
          type: number
          format: double
          example: 4.5

    FridgeMovementDTO:
      type: object
      required:
        - fridge_id
        - sensor_id
        - is_moving
      properties:
        fridge_id:
          type: integer
          example: 123
        sensor_id:
          type: integer
          example: 789
        is_moving:
          type: boolean
          example: true

    ApiResponse:
      type: object
      properties:
        status:
          type: integer
          example: 200
        message:
          type: string
          example: "Success"
