{
 "title": "fridge-bridge",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of current open connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "open_connections{bot=\"fridge-bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests serverd",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "requests_served_total{bot=\"fridge-bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "failed_requests_total{bot=\"fridge-bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "failed_requests_total{bot=\"fridge-bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests served",
   "type": "timeseries",
   "description": "Total requests served",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "requests_served_total", "legendFormat": "__auto" }
   ]
  }
 ]
}