name: Release FridgeBridge

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/fridgebridge.pem
          chmod 600 ~/.ssh/fridgebridge.pem
          cat >>~/.ssh/config <<END
          Host fridgebridge
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/fridgebridge.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy new code
        run: cd repos/fridge-bridge && make deploy-upgrade HOST=fridgebridge
